/** Auto-synced from restroid-cloud — do not hand-edit large maps. */
export const BOSS_ENTITY_LABELS_TR: Record<string, string> = {

  accounting_transaction: "Muhasebe kaydı",
  finance_account: "Finans hesabı",
  supplier: "Tedarikçi",
  supplier_group: "Tedarikçi grubu",
  customer: "Müşteri",
  customer_group: "Müşteri grubu",
  customer_address: "Müşteri adresi",
  crm_sales_quote: "CRM teklifi",
  crm_sales_invoice: "CRM faturası",
  saas_platform_customer: "Kontrol müşterisi",
  saas_platform_customer_group: "Kontrol müşteri grubu",
  saas_platform_supplier: "Kontrol tedarikçisi",
  saas_platform_supplier_group: "Kontrol tedarikçi grubu",
  saas_platform_personnel: "Kontrol personeli",
  saas_platform_personnel_job_definition: "Kontrol görev tanımı",
  saas_platform_warehouse: "Kontrol deposu",
  saas_platform_stock_item: "Kontrol stok kartı",
  saas_platform_service_item: "Kontrol hizmet kartı",
  saas_platform_license_item: "Kontrol lisans ürünü",
  saas_platform_product: "Kontrol CRM ürünü",
  saas_platform_product_category: "Kontrol ürün kategorisi",
  saas_platform_sales_platform: "Kontrol satış platformu",
  super_admin_platform: "Süper admin platform kaydı",
  einvoicing_integration_settings: "E-fatura entegrasyon ayarları",
  saas_crm_restaurant_id: "Platform CRM restoran kapsamı (AppSetting)",
  verimor_sms_integration_settings: "Verimor SMS entegrasyon ayarları",
  verimor_sms_panel_send: "Verimor SMS (panelden gönderim)",
  saas_platform_finance_account: "Kontrol finans hesabı",
  material: "Malzeme",
  material_category: "Malzeme kategorisi",
  product_category: "Ürün kategorisi",
  semi_product: "Ara mamül",
  production: "Üretim",
  stock_move: "Stok hareketi",
  stock_move_in: "Depo giriş fişi",
  stock_move_out: "Depo çıkış fişi",
  operation_log_undo: "Geri alma işlemi",
  service_type_catalog: "Servis türü kataloğu",
  payment_type_definition: "Ödeme tipi (merkez katalog)",
  panel_language_catalog: "Panel dil kataloğu",
  tenant_branch_service_channels: "Şube servis türleri",
  restaurant_preset_note: "Hazır not",
  restaurant_preset_note_type_config: "Not türü ayarları",
  pos_personnel: "POS personeli",
  personnel_job_definition: "Personel görev tanımı",
  personnel_salary_accrual_month: "Personel maaş tahakkuku (ay)",
  personnel_salary_accrual_batch: "Personel tahakkuk grubu (toplu silme)",
  personnel_salary_accrual_cron: "Personel maaş tahakkuku (zamanlanmış)",
  personnel_salary_accrual_auto_login: "Personel maaş tahakkuku (giriş tetiklemesi)",
  personnel_salary_accrual_auto_on_login_setting: "Otomatik tahakkuk (giriş) ayarı",
  product_price_schedule: "İleri tarihli fiyat zamanlaması",
  product_excel_import: "Ürün Excel içe aktarma",
  product_price_excel_import: "Ürün fiyat Excel içe aktarma",
  product_image_upload: "Ürün resmi yükleme (toplu)",
  product_gallery_image_upload: "Ürün ek galeri görseli",
  product_gallery_image_delete: "Ürün ek galeri görseli silme",
  product_gallery_image_reorder: "Ürün galeri görsel sırası",
  product_delete: "Ürün silme",
  product_deactivate_stock_usage: "Ürün pasifleştirme (stok kullanımı)",
  menu_selection_group: "Menü seçim grubu",
  product_preference_group: "Ürün tercihi",
  restaurant_panel_notification: "Şube paneli bildirimi",
  restaurant_panel_notification_read: "Şube paneli bildirimi (okundu)",
  inventory_count: "Envanter sayımı",
  inventory_count_personnel_sheet: "Sayım listesi (personel)",
  warehouse_definition: "Depo tanımı",
  stock_breakdown: "Parçalama işlemi",
  branch_business_profile: "Şube işletme bilgileri",
  restaurant_definitions_branch: "Şube tanımları (işletme)",
  printer_template_master: "Yazıcı şablon master (platform)",
  printer_template_platform_sync: "Yazıcı şablon merkez senkronu",
  printer_template_branch_overrides: "Yazıcı şablon şube seçenekleri",
  tenant_branch_logos: "Şube logoları",
  tenant_payment_type_usage: "Ödeme türü kullanımı (şube)",
  /** Şube POS (Restroid Cloud) satış kapanışı → bulut gelen kutusu */
  restroid_cloud_sales_order: "Restroid Cloud satışı",
  sales_pos_personnel_unlock: "Satış paneli personel PIN girişi",
  tenant_hardware_definitions: "Donanım tanımları (şube)",
  tenant_production_area_definitions: "Üretim yeri tanımları (şube)",
  delivery_region: "Paket teslimat bölgesi",
  service_channel_settings: "Servis kanalı ayarları",
  platform_definition_cache_bypass: "Platform tanım önbelleği (kapatma anahtarı)",
  pos_order_report_template: "POS sipariş rapor şablonu",
  pos_order_report_template_run: "POS sipariş raporu çalıştırma",
  pos_order_report_template_excel: "POS sipariş raporu Excel dışa aktarma",
  accounting_report_template: "Muhasebe rapor şablonu",
  accounting_report_template_run: "Muhasebe raporu önizleme",
  stock_report_template: "Stok rapor şablonu",
  stock_report_template_run: "Stok raporu çalıştırma",
  stock_report_template_excel: "Stok raporu Excel dışa aktarma",
  super_admin_panel_branding: "Süper admin panel markası (sol üst)",
  super_admin_restaurant: "Süper admin restoranı",
  tenant_branch: "Kiracı şubesi",
  saas_platform_unit_definition: "Kontrol birim tanımı",
  saas_platform_tax_rate_definition: "Kontrol KDV tanımı",
  saas_platform_expense_category: "Platform gider ana türü",
  saas_platform_expense_subcategory: "Platform gider alt türü",
  hq_catalog_copy_to_branches: "Merkez katalog şubelere kopyalama",
  hq_group_definitions_copy_to_branches: "Menü ve tercih grupları şubelere kopyalama",

}

export const BOSS_PAGE_LABELS_TR: Record<string, string> = {

  hq_dashboard: "Merkez yönetim paneli",
  hq_branches: "Merkez / Şubeler",
  hq_branch_overview: "Merkez / Şube performansı",
  hq_stock_transfers: "Merkez / Transfer operasyonları",
  hq_stock_inventory_counts: "Merkez / Envanter sayımları",
  hq_stock_inventory_count_expected: "Merkez / Sayımda beklenen stok / fark",
  hq_stock_management: "Merkez / Stok yönetimi",
  hq_menu_management: "Merkez / Menü yönetimi",
  dashboard: "Günün özeti",
  branch_finance: "Finans",
  orders: "Siparişler",
  products: "Ürünler",
  customers: "Müşteriler",
  suppliers: "Tedarikçiler",
  accounting: "Muhasebe",
  stock_management: "Stok yönetimi",
  stock_inventory_counts: "Envanter sayımları",
  stock_inventory_count_expected: "Sayımda beklenen stok / fark",
  stock_transfers: "Stok transferleri",
  branches: "Şubeler",
  branch_overview: "Şube özet",
  definitions: "Tanımlar",
  definitions_salon_masa: "Tanımlar / Salon-Masa",
  definitions_services: "Tanımlar / Servis türleri",
  definitions_working_hours: "Tanımlar / Çalışma saatleri",
  definitions_restaurant: "Tanımlar / İşletme",
  definitions_finance: "Tanımlar / Finans",
  definitions_hardware: "Tanımlar / Donanım",
  definitions_production_areas: "Tanımlar / Üretim yerleri",
  definitions_pos_roles: "Personel / Terminal yetkileri (POS rolleri)",
  personnel: "Personel",
  settings: "Ayarlar",
  qr_menu: "Entegrasyonlar / QR menü",
  panel_roles: "Panel yetkileri",
  panel_users: "Panel kullanıcıları",
  surveys: "Anketler",
  operation_logs: "İşlem hareketleri",
  super_admin_restaurants: "Süper admin / Restoranlar",
  super_admin_license_sales: "Süper admin / Lisans satışı",
  super_admin_invitations: "Süper admin / Davetler",
  super_admin_users: "Süper admin / Kullanıcılar",
  super_admin_admin_users: "Süper admin / Admin kullanıcılar",
  super_admin_admin_roles: "Süper admin / Admin roller",
  super_admin_platforms: "Süper admin / Platformlar",
  super_admin_announcements: "Süper admin / Duyurular",
  super_admin_activity_logs: "Süper admin / Activity logs",
  super_admin_mail_logs: "Süper admin / Mail logları",
  super_admin_messages: "Süper admin / Mesajlar (SMS)",
  super_admin_system_error_logs: "Süper admin / Sistem hata logları",
  super_admin_security_firewall: "Süper admin / Security firewall",
  super_admin_settings: "Süper admin / Ayarlar",
  super_admin_profile: "Süper admin / Profil bilgileri",
  super_admin_definitions: "Süper admin / Tanımlar",
  super_admin_tenant_health: "Süper admin / Restoran bulut durumu",
  super_admin_branches: "Süper admin / Şubeler",
  super_admin_transfers: "Süper admin / Transferler",
  super_admin_branch_overview: "Süper admin / Şube özet",
  super_admin_saas_crm: "Süper admin / Platform CRM",
  super_admin_saas_platform: "Süper admin / Platform işletmesi (CRM, muhasebe, stok)",

}

export const BOSS_PAGE_LABELS_EN: Record<string, string> = {

  hq_dashboard: "Head office dashboard",
  hq_branches: "Head office / Branches",
  hq_branch_overview: "Head office / Branch overview",
  hq_stock_transfers: "Head office / Stock transfers",
  hq_stock_inventory_counts: "Head office / Inventory counts",
  hq_stock_inventory_count_expected: "Head office / Count expected qty / variance",
  hq_stock_management: "Head office / Stock management",
  hq_menu_management: "Head office / Menu management",
  dashboard: "Today’s overview",
  branch_finance: "Finance",
  orders: "Orders",
  products: "Products",
  customers: "Customers",
  suppliers: "Suppliers",
  accounting: "Accounting",
  stock_management: "Stock management",
  stock_inventory_counts: "Inventory counts",
  stock_inventory_count_expected: "Count expected qty / variance",
  stock_transfers: "Stock transfers",
  branches: "Branches",
  branch_overview: "Branch overview",
  definitions: "Definitions",
  definitions_salon_masa: "Definitions / Areas-Tables",
  definitions_services: "Definitions / Service types",
  definitions_working_hours: "Definitions / Working hours",
  definitions_restaurant: "Definitions / Business",
  definitions_finance: "Definitions / Finance",
  definitions_hardware: "Definitions / Hardware",
  definitions_production_areas: "Definitions / Production areas",
  definitions_pos_roles: "Personnel / Terminal permissions (POS roles)",
  personnel: "Personnel",
  settings: "Settings",
  qr_menu: "Integrations / QR menu",
  panel_roles: "Panel permissions",
  panel_users: "Panel users",
  surveys: "Surveys",
  operation_logs: "Operation logs",
  super_admin_restaurants: "Super admin / Restaurants",
  super_admin_license_sales: "Super admin / License sales",
  super_admin_invitations: "Super admin / Invitations",
  super_admin_users: "Super admin / Users",
  super_admin_admin_users: "Super admin / Admin users",
  super_admin_admin_roles: "Super admin / Admin roles",
  super_admin_platforms: "Super admin / Platforms",
  super_admin_announcements: "Super admin / Announcements",
  super_admin_activity_logs: "Super admin / Activity logs",
  super_admin_mail_logs: "Super admin / Mail logs",
  super_admin_messages: "Super admin / Messages (SMS)",
  super_admin_system_error_logs: "Super admin / System error logs",
  super_admin_security_firewall: "Super admin / Security firewall",
  super_admin_settings: "Super admin / Settings",
  super_admin_profile: "Super admin / Profile",
  super_admin_definitions: "Super admin / Definitions",
  super_admin_tenant_health: "Super admin / Restaurant cloud status",
  super_admin_branches: "Super admin / Branches",
  super_admin_transfers: "Super admin / Transfers",
  super_admin_branch_overview: "Super admin / Branch overview",
  super_admin_saas_crm: "Super admin / Platform CRM",
  super_admin_saas_platform: "Super admin / Platform business (CRM, accounting, stock)",

}
